name: envar tutorial
env: 
  WORKFLOW_VARIABLE: "this is a work flow variable"
  DAY_OF_WEEK: "Monday"
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      JOB_VARIABLE: "this is a job variable"
      
    steps:
      - name: print environment variables
        env:
          STEP_VARIABLE: "this is a step variable"
        run: |
          echo my variables
          echo workflow ${{ env.WORKFLOW_VARIABLE }}
          echo job ${{ env.JOB_VARIABLE }}
          echo step ${{ env.STEP_VARIABLE }}
      - name: say hello if monday
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo hello on ${{ env.DAY_OF_WEEK }}
        
